language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t grochap/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true grochap/docker-react npm run test